repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "cef0300fd0fc4d2a87a85fa2093c6b283ea36f4b" # v5.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "586c3ea3f51230da42bab657c6a32e9e66c364f0" # v0.44.0
    hooks:
      - id: markdownlint
        args:
          - --fix
  - repo: https://github.com/tillig/json-sort-cli
    rev: "e49ea86dde26d69661d5de4ab738a7e14c6275b2" # v2.0.3
    hooks:
      - id: json-sort
        args:
          - --autofix
