repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "3e8a8703264a2f4a69428a0aa4dcb512790b2c8c"  # frozen: v6.0.0
    hooks:
      - id: check-json
      - id: check-yaml
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: "e72a3ca1632f0b11a07d171449fe447a7ff6795e"  # frozen: v0.48.0
    hooks:
      - id: markdownlint
        args:
          - --fix
  - repo: https://github.com/tillig/json-sort-cli
    rev: "2b7e147e0933bd30b58133b6f287e5c695ff4f0e"  # frozen: v3.0.1
    hooks:
      - id: json-sort
        args:
          - --autofix
