//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2.6.1.841")]
[assembly: AssemblyFileVersion("2.6.1.841")]
[assembly: AssemblyConfiguration("Release built on 2012-03-05 11:24")]


[assembly: System.Security.SecurityTransparent]
[assembly: System.Security.SecurityRules(System.Security.SecurityRuleSet.Level2)]
