//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1378
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ContainerResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ContainerResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.ContainerResources", typeof(ContainerResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At least one service is required per component registration..
        /// </summary>
        internal static string AtLeastOneService {
            get {
                return ResourceManager.GetString("AtLeastOneService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection item type {0} has already been registered as a single-valued service. Register the collection before adding instances to it..
        /// </summary>
        internal static string CollectionItemTypeRegisteredAsService {
            get {
                return ResourceManager.GetString("CollectionItemTypeRegisteredAsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} service is exposed multiple times by the same component..
        /// </summary>
        internal static string ComponentExposesServiceMultipleTimes {
            get {
                return ResourceManager.GetString("ComponentExposesServiceMultipleTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A component named &apos;{0}&apos; has already been registered. Component names must be unique within a container..
        /// </summary>
        internal static string RegistrationNameNotUnique {
            get {
                return ResourceManager.GetString("RegistrationNameNotUnique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided registration does not support the required service..
        /// </summary>
        internal static string RequiredServiceNotSupported {
            get {
                return ResourceManager.GetString("RequiredServiceNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service types cannot be null..
        /// </summary>
        internal static string ServiceTypesCannotBeNull {
            get {
                return ResourceManager.GetString("ServiceTypesCannotBeNull", resourceCulture);
            }
        }
    }
}
