//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///    A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RegistrationExtensionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        internal RegistrationExtensionsResources() {
        }
        
        /// <summary>
        ///    Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.RegistrationExtensionsResources", typeof(RegistrationExtensionsResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///    Overrides the current thread's CurrentUICulture property for all
        ///    resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to The instance  registration &apos;{0}&apos; can support SingleInstance() sharing only..
        /// </summary>
        public static string InstanceRegistrationsAreSingleInstanceOnly {
            get {
                return ResourceManager.GetString("InstanceRegistrationsAreSingleInstanceOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to A metadata attribute of type &apos;{0}&apos; was not found on &apos;{1}&apos;..
        /// </summary>
        public static string MetadataAttributeNotFound {
            get {
                return ResourceManager.GetString("MetadataAttributeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to More than one metadata attribute of type &apos;{0}&apos; was found on &apos;{1}&apos;..
        /// </summary>
        public static string MultipleMetadataAttributesSameType {
            get {
                return ResourceManager.GetString("MultipleMetadataAttributesSameType", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to No matching constructor exists on type &apos;{0}&apos;..
        /// </summary>
        public static string NoMatchingConstructorExists {
            get {
                return ResourceManager.GetString("NoMatchingConstructorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///    Looks up a localized string similar to You can only attach a registration predicate to a registration that has a callback container attached (e.g., one that was made with a standard ContainerBuilder extension method)..
        /// </summary>
        public static string OnlyIfRequiresCallbackContainer {
            get {
                return ResourceManager.GetString("OnlyIfRequiresCallbackContainer", resourceCulture);
            }
        }
    }
}
