//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Autofac.Diagnostics {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TracerMessages {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TracerMessages() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Autofac.Diagnostics.TracerMessages", typeof(TracerMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Component: {0}.
        /// </summary>
        internal static string ComponentDisplay {
            get {
                return ResourceManager.GetString("ComponentDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to -&gt; {0}.
        /// </summary>
        internal static string EnterMiddleware {
            get {
                return ResourceManager.GetString("EnterMiddleware", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to {.
        /// </summary>
        internal static string EntryBrace {
            get {
                return ResourceManager.GetString("EntryBrace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Exception: {0}.
        /// </summary>
        internal static string ExceptionDisplay {
            get {
                return ResourceManager.GetString("ExceptionDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to }.
        /// </summary>
        internal static string ExitBrace {
            get {
                return ResourceManager.GetString("ExitBrace", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to X- {0}.
        /// </summary>
        internal static string ExitMiddlewareFailure {
            get {
                return ResourceManager.GetString("ExitMiddlewareFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to &lt;- {0}.
        /// </summary>
        internal static string ExitMiddlewareSuccess {
            get {
                return ResourceManager.GetString("ExitMiddlewareSuccess", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Instance: {0}.
        /// </summary>
        internal static string InstanceDisplay {
            get {
                return ResourceManager.GetString("InstanceDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operation FAILED.
        /// </summary>
        internal static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Operation Succeeded; result instance was {0}.
        /// </summary>
        internal static string OperationSucceeded {
            get {
                return ResourceManager.GetString("OperationSucceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cannot outdent; no indentation specified..
        /// </summary>
        internal static string OutdentFailure {
            get {
                return ResourceManager.GetString("OutdentFailure", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pipeline:.
        /// </summary>
        internal static string Pipeline {
            get {
                return ResourceManager.GetString("Pipeline", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolve Operation Starting.
        /// </summary>
        internal static string ResolveOperationStarting {
            get {
                return ResourceManager.GetString("ResolveOperationStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolve Request FAILED.
        /// </summary>
        internal static string ResolveRequestFailed {
            get {
                return ResourceManager.GetString("ResolveRequestFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolve Request FAILED: Nested Resolve Failed.
        /// </summary>
        internal static string ResolveRequestFailedNested {
            get {
                return ResourceManager.GetString("ResolveRequestFailedNested", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolve Request Starting.
        /// </summary>
        internal static string ResolveRequestStarting {
            get {
                return ResourceManager.GetString("ResolveRequestStarting", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Resolve Request Succeeded; result instance was {0}.
        /// </summary>
        internal static string ResolveRequestSucceeded {
            get {
                return ResourceManager.GetString("ResolveRequestSucceeded", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Service: {0}.
        /// </summary>
        internal static string ServiceDisplay {
            get {
                return ResourceManager.GetString("ServiceDisplay", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to You may not add or remove subscriptions on this tracer. This ensures all required events are properly captured and traces can be correctly handled..
        /// </summary>
        internal static string SubscriptionsDisabled {
            get {
                return ResourceManager.GetString("SubscriptionsDisabled", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Target: {0}.
        /// </summary>
        internal static string TargetDisplay {
            get {
                return ResourceManager.GetString("TargetDisplay", resourceCulture);
            }
        }
    }
}
