//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("1.4.4.565")]
[assembly: AssemblyFileVersion("1.4.4.565")]
[assembly: AssemblyConfiguration("Release built on 2009-07-31 22:08")]


[assembly: System.Security.AllowPartiallyTrustedCallers]
