//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30128.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2.1.10.754")]
[assembly: AssemblyFileVersion("2.1.10.754")]
[assembly: AssemblyConfiguration("Release built on 2010-02-12 21:27")]


[assembly: System.Security.AllowPartiallyTrustedCallers]
