//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.372
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2.4.2.696")]
[assembly: AssemblyFileVersion("2.4.2.696")]
[assembly: AssemblyConfiguration("Release built on 2011-01-25 07:20")]


[assembly: System.Security.AllowPartiallyTrustedCallers]
