//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2.3.1.530")]
[assembly: AssemblyFileVersion("2.3.1.530")]
[assembly: AssemblyConfiguration("Release built on 2010-08-19 10:16")]


[assembly: System.Security.AllowPartiallyTrustedCallers]
