//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.21006.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyVersion("2.1.5.705")]
[assembly: AssemblyFileVersion("2.1.5.705")]
[assembly: AssemblyConfiguration("Release built on 2009-12-31 16:53")]


[assembly: System.Security.AllowPartiallyTrustedCallers]
