name: Build and Test
on:
  pull_request:
    branches:
      - develop
      - master
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 6
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Setup .NET 7
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 7.0.x
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Build and test
      run: dotnet msbuild ./default.proj

# TODO: Can we parse the build output logs to provide better warning/error feedback?
# TODO: Add dotnet format as a lint step in the build.
# TODO: Upload to CodeCov should be part of the GitHub actions.
# TODO: Upload to GitHub packages instead of MyGet in GitHub actions for master and develop.
