name: Continuous Integration
on:
  pull_request:
    branches:
      - develop
      - master
  push:
# If multiple pushes happen quickly in succession, cancel the running build and
# start a new one.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  # Linting
  dotnet-format:
    uses: ./.github/workflows/dotnet-format.yml
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  # Build and test
  build:
    uses: ./.github/workflows/build.yml
