name: Continuous Integration
on:
  pull_request:
    branches:
      - develop
      - master
  push:
    branches:
      - develop
      - master
      - feature/*
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
# If multiple pushes happen quickly in succession, cancel the running build and
# start a new one.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  # Linting
  dotnet-format:
    uses: ./.github/workflows/dotnet-format.yml
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  # Build and test
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  # Publish beta and release packages.
  publish:
    uses: ./.github/workflows/publish.yml
    needs:
      - build
      - dotnet-format
      - pre-commit
    if: ${{ github.ref == 'refs/heads/develop' || startsWith(github.ref, 'refs/tags/v') }}
    secrets:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
