name: Continuous Integration
on:
  pull_request:
    branches:
      - develop
      - master
  push:
jobs:
  # Linting
  dotnet-format:
    uses: ./.github/workflows/dotnet-format.yml
  pre-commit:
    uses: ./.github/workflows/pre-commit.yml
  # Build and test
  build:
    uses: ./.github/workflows/build.yml
